### ISSUE TITLE
Great job! But pretrained_ckpt load erroe;

### ISSUE THREAD

**Issue by Byronnar** [HuCaoFighting/Swin-Unet#13]
When I train with my datasets, the error occured as below:
```
=> merge config from configs/swin_tiny_patch4_window7_224_lite.yaml
SwinTransformerSys expand initial----depths:[2, 2, 2, 2];depths_decoder:[1, 2, 2, 2];drop_path_rate:0.2;num_classes:9
---final upsample expand_first---
pretrained_path:./pretrained_ckpt/swin_tiny_patch4_window7_224.pth
Traceback (most recent call last):
  File "train.py", line 96, in <module>
    net.load_from(config)
  File "/mnt/e/projects/Sementic_Segmentation/Swin-Unet-PyTorch/networks/vision_transformer.py", line 58, in load_from
    pretrained_dict = torch.load(pretrained_path, map_location=device)
  File "/home/byronnar/anaconda3/envs/swin_unet_torch/lib/python3.7/site-packages/torch/serialization.py", line 527, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/home/byronnar/anaconda3/envs/swin_unet_torch/lib/python3.7/site-packages/torch/serialization.py", line 224, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fd2bbfab193 in /home/byronnar/anaconda3/envs/swin_unet_torch/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x1f5b (0x7fd2bf1339eb in /home/byronnar/anaconda3/envs/swin_unet_torch/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::string const&) + 0x64 (0x7fd2bf134c04 in /home/byronnar/anaconda3/envs/swin_unet_torch/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x6c6536 (0x7fd307246536 in /home/byronnar/anaconda3/envs/swin_unet_torch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x295a74 (0x7fd306e15a74 in /home/byronnar/anaconda3/envs/swin_unet_torch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #33: __libc_start_main + 0xf3 (0x7fd319cf10b3 in /lib/x86_64-linux-gnu/libc.so.6)
```
How should I do? Thank you!

**Comment by Byronnar** [comment]
install 
torch==1.6.0
torchvision==0.7.0
Can solve this problem.
