### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by Lsysslsyss** [HuCaoFighting/Swin-Unet#36]
=> merge config from configs/swin_tiny_patch4_window7_224_lite.yaml
SwinTransformerSys expand initial----depths:[2, 2, 2, 2];depths_decoder:[1, 2, 2, 2];drop_path_rate:0.2;num_classes:9
---final upsample expand_first---
pretrained_path:./pretrained_ckpt/swin_tiny_patch4_window7_224.pth
---start load pretrained modle of swin encoder---
Namespace(accumulation_steps=None, amp_opt_level='O1', base_lr=0.01, batch_size=1, cache_mode='part', cfg='configs/swin_tiny_patch4_window7_224_lite.yaml', dataset='Synapse', deterministic=1, eval=False, img_size=12, list_dir='./lists/lists_Synapse', max_epochs=150, max_iterations=30000, n_gpu=1, num_classes=9, opts=None, output_dir='.\\model_out\\', resume=None, root_path='.\\datasets\\Synapse\\train_npz', seed=1234, tag=None, throughput=False, use_checkpoint=False, zip=False)
The length of train set is: 2211
2211 iterations per epoch. 331650 max iterations
  0%|                                         | 0/150 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 99, in <module>
    trainer[dataset_name](args, net, args.output_dir)
  File "C:\Users\Downloads\Swin-Unet-main\trainer.py", line 53, in trainer_synapse
    for i_batch, sampled_batch in enumerate(trainloader):
  File "C:\anaconda\envs\swin\lib\site-packages\torch\utils\data\dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\anaconda\envs\swin\lib\site-packages\torch\utils\data\dataloader.py", line 737, in __init__
    w.start()
  File "C:\anaconda\envs\swin\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\anaconda\envs\swin\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\anaconda\envs\swin\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\anaconda\envs\swin\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\anaconda\envs\swin\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'trainer_synapse.<locals>.worker_init_fn'

**Comment by qingkuangshu** [comment]
Are you running this code?

**Comment by YumnaMemon** [comment]
have you solved it?
