### ISSUE TITLE
分割结果边缘呈现阶梯锯齿状

### ISSUE THREAD

**Issue by 670973787** [HuCaoFighting/Swin-Unet#70]
It is a nice job! However I have some problem when training my own dataset.

我在用自己的数据集做心脏分割，没有使用预训练模型，网络结构基本采用默认参数没有任何调整，只是把输入的image size改成了448*448。但是分割结果的边缘呈现阶梯锯齿状而不是平滑的边缘，训练集和预测集都有这样的问题。

想请教作者是否也曾遇到过这样的问题？

Thanks

**Comment by HuCaoFighting** [comment]
对于pure transformer的model必须要使用pre-trained，不然的话效果会差很多。你输入图像尺寸改变的同时，可以参考swin transformer的high resolution的config。swin的最后的window size要和最后一层的尺寸保持一致，这样他可以实现最后的global attention。不想出现分割结果的边缘呈现阶梯锯齿状，得到比较平滑的边缘，可以增加conv等local operation这样可以增加局部细节，一般non-overlap的 patch划分是会出现边缘不够平滑的问题。

**Comment by 670973787** [comment]
Thank you very much for your reply. It is very helpful.

Best.

**Comment by ZSK0011** [comment]
> 
您好！用自己训练集的话，怎么设置图片和标签的路径？

**Comment by Polar-1** [comment]
> 这是一份不错的工作！但是，在训练自己的数据集时，我遇到了一些问题。
> 
> 我在用自己的数据集做心脏分割，没有使用预训练模型，网络结构基本采用默认参数没有任何调整，只是把输入的image size改成了448*448。但是分割结果的边缘呈现阶梯锯齿状而不是平滑的边缘，训练集和预测集都有这样的问题。
> 
> 想请教作者是否也曾遇到过这样的问题？
> 
> 谢谢

我想问问更改训练的分辨率需要更改哪些地方？我直接更改train.py中的分辨率会报错：AssertionError: Input image size (448*448) doesn't match model (224*224).

**Comment by Polar-1** [comment]
> It is a nice job! However I have some problem when training my own dataset.
> 
> 我在用自己的数据集做心脏分割，没有使用预训练模型，网络结构基本采用默认参数没有任何调整，只是把输入的image size改成了448*448。但是分割结果的边缘呈现阶梯锯齿状而不是平滑的边缘，训练集和预测集都有这样的问题。
> 
> 想请教作者是否也曾遇到过这样的问题？
> 
> Thanks

我想问问更改训练的分辨率需要更改哪些地方？我直接更改train.py中的分辨率会报错：AssertionError: Input image size (448448) doesn't match model (224224).

Thanks.

**Comment by guiguiguiguigui** [comment]
> > 这是一份不错的工作！但是，我在训练自己的数据集时遇到了一些问题。
> > 我在用自己的数据集做心脏分割，没有使用预训练模型，网络结构基本采用默认参数没有任何调整，只是把输入的image size改成了448*448。但是分割结果的边缘呈现阶梯锯齿状而不是平滑的边缘，训练集和预测集都有这样的问题。
> > 想请教作者是否也曾遇到过这样的问题？
> > 谢谢
> 
> 我想问问更改训练的分辨率需要更改哪些地方？我直接更改 train.py 中的分辨率会报错：AssertionError： Input image size （448448） doesn't match model （224224）。
> 
> 谢谢。

我也想要问这个问题，兄弟，你解决了吗？请问

**Comment by 1291454630** [comment]
> 对于pure transformer的model必须要使用pre-trained，不然的话效果会差很多。你输入图像尺寸改变的同时，可以参考swin transformer的high resolution的config。swin的最后的window size要和最后一层的尺寸保持一致，这样他可以实现最后的global attention。不想出现分割结果的边缘呈现阶梯锯齿状，得到比较平滑的边缘，可以增加conv等local operation这样可以增加局部细节，一般non-overlap的 patch划分是会出现边缘不够平滑的问题。

This is very useful. Thanks for your answer!

**Comment by congcongwy51** [comment]
你好，我想问问您最后怎么解决锯齿问题的？ @peterant330

**Comment by 1291454630** [comment]
把config里的window size设置成你的 图像大小÷bottleneck部分中图像size缩小的倍数。我当时是这么做的，不过因为预训练是作者医学分割的，所以结果也不是特别好，但是锯齿状的问题有所改善



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月11日(周五) 下午4:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HuCaoFighting/Swin-Unet] 分割结果边缘呈现阶梯锯齿状 (Issue #70)




 
你好，我想问问您最后怎么解决锯齿问题的？ @peterant330

**Comment by congcongwy51** [comment]
您好，我输入256*256
但是256/32=8，我将window_size设置成8，报错Traceback (most recent call last):
  File "Swin-Unet/train.py", line 95, in <module>
    net = ViT_seg(config, img_size=args.img_size, num_classes=args.num_classes).cuda()
  File "/root/Swin-Unet/networks/vision_transformer.py", line 30, in __init__
    self.swin_unet = SwinTransformerSys(img_size=config.DATA.IMG_SIZE,
  File "/root/Swin-Unet/networks/swin_transformer_unet_skip_expand_decoder_sys.py", line 727, in __init__
    layer = BasicLayer(dim=int(embed_dim * 2 ** i_layer),
  File "/root/Swin-Unet/networks/swin_transformer_unet_skip_expand_decoder_sys.py", line 451, in __init__
    self.blocks = nn.ModuleList([
  File "/root/Swin-Unet/networks/swin_transformer_unet_skip_expand_decoder_sys.py", line 452, in <listcomp>
    SwinTransformerBlock(dim=dim, input_resolution=input_resolution,
  File "/root/Swin-Unet/networks/swin_transformer_unet_skip_expand_decoder_sys.py", line 253, in __init__
    mask_windows = window_partition(img_mask, self.window_size)  # nW, window_size, window_size, 1
  File "/root/Swin-Unet/networks/swin_transformer_unet_skip_expand_decoder_sys.py", line 38, in window_partition
    x = x.view(B, H // window_size, window_size, W // window_size, window_size, C)
RuntimeError: shape '[1, 3, 8, 3, 8, 1]' is invalid for input of size 784 @peterant330

**Comment by 1291454630** [comment]
这个你用GPT之类的ai试试吧，光看这个我也看不懂😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月11日(周五) 晚上7:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HuCaoFighting/Swin-Unet] 分割结果边缘呈现阶梯锯齿状 (Issue #70)




 
您好，我输入256*256
 但是256/32=8，我将window_size设置成8，报错Traceback (most recent call last):
 File "Swin-Unet/train.py", line 95, in 
 net = ViT_seg(config, img_size=args.img_size, num_classes=args.num_classes).cuda()
 File "/root/Swin-Unet/networks/vision_transformer.py", line 30, in init
 self.swin_unet = SwinTransformerSys(img_size=config.DATA.IMG_SIZE,
 File "/root/Swin-Unet/networks/swin_transformer_unet_skip_expand_decoder_sys.py", line 727, in init
 layer = BasicLayer(dim=int(embed_dim * 2 ** i_layer),
 File "/root/Swin-Unet/networks/swin_transformer_unet_skip_expand_decoder_sys.py", line 451, in init
 self.blocks = nn.ModuleList([
 File "/root/Swin-Unet/networks/swin_transformer_unet_skip_expand_decoder_sys.py", line 452, in 
 SwinTransformerBlock(dim=dim, input_resolution=input_resolution,
 File "/root/Swin-Unet/networks/swin_transformer_unet_skip_expand_decoder_sys.py", line 253, in init
 mask_windows = window_partition(img_mask, self.window_size)  # nW, window_size, window_size, 1
 File "/root/Swin-Unet/networks/swin_transformer_unet_skip_expand_decoder_sys.py", line 38, in window_partition
 x = x.view(B, H // window_size, window_size, W // window_size, window_size, C)
 RuntimeError: shape '[1, 3, 8, 3, 8, 1]' is invalid for input of size 784 @peterant330

**Comment by EleFreelance** [comment]
@HuCaoFighting 我使用了image-net pretrain的模型，完全使用你的codebase，但是把数据集加载部分替换掉了，同样出现了这个问题。 边缘锯齿感严重， 我好奇，你在训练时，使用image-net pratrain的模型就没出现过吗？ 是否跟调参训练有关？  
我能确认的是数据集没有问题，因为我换成Unet网络，表现效果是完全正常的。

**Comment by congcongwy51** [comment]
我更改了until.py，我觉得是他缩放问题导致锯齿问题，我更改后，锯齿状有缓解。

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2025年02月13日 21:06 |
| 收件人 | HuCaoFighting/Swin-Unet ***@***.***> |
| 抄送人 | congcongwy51 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [HuCaoFighting/Swin-Unet] 分割结果边缘呈现阶梯锯齿状 (Issue #70) |

@HuCaoFighting 我使用了image-net pretrain的模型，完全使用你的codebase，但是把数据集加载部分替换掉了，同样出现了这个问题。 边缘锯齿感严重， 我好奇，你在训练时，使用image-net pratrain的模型就没出现过吗？ 是否跟调参训练有关？
我能确认的是数据集没有问题，因为我换成Unet网络，表现效果是完全正常的。
