### ISSUE TITLE
训练时报错：zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by wangru1026** [HuCaoFighting/Swin-Unet#72]
训练跑了200+轮后时出现：

Traceback (most recent call last):
  File "train.py", line 99, in <module>
    trainer[dataset_name](args, net, args.output_dir)
  File "/root/Swin-Unet-main/trainer.py", line 53, in trainer_synapse
    for i_batch, sampled_batch in enumerate(trainloader):
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
zipfile.BadZipFile: Caught BadZipFile in DataLoader worker process 6.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/Swin-Unet-main/datasets/dataset_synapse.py", line 63, in __getitem__
    data = np.load(data_path)
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    ret = NpzFile(fid, own_fid=own_fid, allow_pickle=allow_pickle,
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/numpy/lib/npyio.py", line 180, in __init__
    _zip = zipfile_factory(fid)
  File "/root/anaconda3/envs/pytorch/lib/python3.8/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/root/anaconda3/envs/pytorch/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/root/anaconda3/envs/pytorch/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
请问有没有大佬知道怎么解决？

**Comment by YumnaMemon** [comment]
Have you solved this problem?

**Comment by a13049162951** [comment]
I also encountered this problem, how did you solve it?

**Comment by HangS666** [comment]
我跑的结果也很差dice接近0是什么原因造成的
