### ISSUE TITLE
报错问题

### ISSUE THREAD

**Issue by xushengweihf** [HuCaoFighting/Swin-Unet#92]
Traceback (most recent call last):
  File "/home/xxx/Swin-Unet/train.py", line 10, in <module>
    from config import get_config
  File "/home/xxx/Swin-Unet/config.py", line 72, in <module>
    _C.MODEL.SWIN.QK_SCALE = None
  File "/home/xxxo/miniconda3/envs/xsw_torch/lib/python3.8/site-packages/yacs/config.py", line 155, in __setattr__
    _assert_with_logging(
  File "/home/xxx/miniconda3/envs/xsw_torch/lib/python3.8/site-packages/yacs/config.py", line 521, in _assert_with_logging
    assert cond, msg
AssertionError: Invalid type <class 'NoneType'> for key QK_SCALE; valid types = {<class 'tuple'>, <class 'list'>, <class 'str'>, <class 'int'>, <class 'float'>, <class 'bool'>}

**Comment by xushengweihf** [comment]
各位大佬好，可以发一份acdc数据集的预处理代码吗，我的邮箱地址[591218250@qq.com](mailto:591218250@qq.com), 万分感谢，祝您科研顺利。
